name: "[Helseforetakets navn]"
encoding: UTF-8
category-list: [202197-Lukke-knapp som følger behandlingsprogrammet, Nytt søk/filter for behandling, Utlistinger behandlinger/avdelinger/kliniske studier, Annet, Tidligere releaser, ]
customer-list: [HF, RHF, IKT, Felleskomponenter]

source: 'src/jekyll'
destination: dist/
keep_files: [assets/js, assets/css, maps, assets/Images]
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
